#!/usr/bin/env bash

ROFI_THEMES_PATH="${HOME}/.config/rofi/themes/colors"
QTILE_COLORS_PATH="${HOME}/.config/qtile/colors.py"
QTILE_THEME_CURRENT="$(cat $QTILE_COLORS_PATH | awk -F '=' '/default/ {print $2}' | xargs)"
KITTY_CONFIG_PATH="${HOME}/.config/kitty"
WAYBAR_THEME_PATH="${HOME}/.config/waybar/themes"
DUNST_THEME_PATH="${HOME}/.config/dunst/themes"
WALLPAPER_DIR="${HOME}/Pictures/wallpapers"

THEMES=(
	"Catppuccin"
	"Dracula"
	"EverforestDarkHard"
	"GruvBox"
	"Nord"
	"SpringBlossom"
	"Tokyonight"
	)

function apply_theme(){

	FIND="default = $QTILE_THEME_CURRENT"
	REPLACE="default = $THEME_CHOICE"

	#rofi
	cp "$ROFI_THEMES_PATH/$THEME_CHOICE.rasi" "$ROFI_THEMES_PATH/default.rasi"
	
	#qtile
	sed -i "s/$FIND/$REPLACE/g" "$QTILE_COLORS_PATH"

	#hypr and sway
	cp "$WAYBAR_THEME_PATH/$THEME_CHOICE.css" "$WAYBAR_THEME_PATH/default.css"

	#kitty
	cp "$KITTY_CONFIG_PATH/$THEME_CHOICE.conf" "$KITTY_CONFIG_PATH/default.conf" 

	#dunst
	cp "$DUNST_THEME_PATH/$THEME_CHOICE" "$DUNST_THEME_PATH/../dunstrc"
	killall dunst && dunst

	# wallpaper
	cp "$WALLPAPER_DIR/$THEME_CHOICE".* "$WALLPAPER_DIR/default"

	if [[ "$DESKTOP_SESSION" == "qtile" ]]; then
		feh --bg-fill "$WALLPAPER_DIR/default" &
	elif [[ "$DESKTOP_SESSION" == "sway" ]]; then
		swaybg -i "$WALLPAPER_DIR/default" &
	else 
		echo "Failed to set wallpaper"
	fi

	if [[ "$DESKTOP_SESSION" == "qtile" ]]; then
		qtile cmd-obj -o cmd -f restart 
	elif [[ "$DESKTOP_SESSION" == "sway" ]]; then
		swaymsg reload &
		killall waybar &
		waybar -c "${HOME}/.config/waybar/sway/config.jsonc" -s "${HOME}/.config/waybar/sway/style.css" &
	elif [[ "$DESKTOP_SESSION" == "hyprland" ]]; then
		hyprctl reload &
		killall waybar &
		waybar -c "${HOME}/.config/waybar/hypr/config.jsons" -s "${HOME}/.config/waybar/hypr/style.css" &
	else 
		echo "Neither sway nor hyprland is installed."
	fi


}

THEME_CHOICE=$(printf '%s\n' "${THEMES[@]}" | rofi -dmenu -p "Select a theme:")

if [[ -n "$THEME_CHOICE" ]]; then
    echo "You selected: $THEME_CHOICE"
    echo "Applying theme..."
    apply_theme
    echo "Done"
else
    echo "No valid selection made."
fi
