"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_red)\
$os\
$username\
[](bg:color_orange fg:color_red)\
$directory\
[](fg:color_orange bg:color_red)\
$git_branch\
$git_status\
[](fg:color_red bg:color_orange)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_orange bg:color_red)\
$docker_context\
$conda\
[](fg:color_red bg:color_red)\
$time\
[ ](fg:color_red)\
$line_break"""

palette = 'rosepine'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.rosepine]
color_fg0 = '#e0def4'
color_fg1 = '#2a273f'
color_bg1 = '#3e8fb0'
color_bg3 = '#9ccfd8'
color_blue = '#56949f'
color_aqua = '#3e8fb0'
color_green = '#c4a7e7'
color_orange = '#ebbcba'
color_purple = '#C6A0F6'
color_red = '#eb6f92'
color_yellow = '#ea9d34'
color_love = '#b4637a'
color_love2 = '#eb6f92'

[os]
disabled = false
style = "bg:color_red fg:color_fg1"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
openSUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "

[username]
show_always = false
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "bold fg:color_fg1 bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_red)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg1 bg:color_red)]($style)'

[nodejs]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[c]
symbol = " "
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[rust]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[golang]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[php]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[java]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[kotlin]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[haskell]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[python]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_orange)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](bold fg:color_fg1 bg:color_red)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
