import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Medium"}
bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
size = 11.00
