#!/bin/bash
#______ _   _ _____                       _   _
#| ___ \ | | /  ___|                     | | | |
#| |_/ / | | \ `--. _ __ ___   ___   ___ | |_| |__
#|    /| | | |`--. \ '_ ` _ \ / _ \ / _ \| __| '_ \
#| |\ \\ \_/ /\__/ / | | | | | (_) | (_) | |_| | | |
#\_| \_|\___/\____/|_| |_| |_|\___/ \___/ \__|_| |_|
#
# Copyright (c) 2024 rvsmooth
# https://github.com/rvsmooth

ROFI_DIR="$HOME/.config/rofi"
ROFI_SCRIPTS_DIR="$ROFI_DIR/scripts"
UTILS=(
  "AppDrawer"
  "Bluetooth"
  "Bluetooth-bzmenu"
  "Brightness"
  "ColorShift"
  "ClipBoard"
  "Emojis"
  "PowerMenu"
  "Themer"
  "WifiMenu"
  "WifiMenu-iwmenu"
)

ROFI_UTILS_CMD=$(printf '%s\n' "${UTILS[@]}" | rofi -dmenu -i -p "Utilities")
if [ -n "$ROFI_UTILS_CMD" ]; then
  bash $ROFI_SCRIPTS_DIR/$ROFI_UTILS_CMD
else
  exit 1
fi
