#!/bin/bash
#______ _   _ _____                       _   _     
#| ___ \ | | /  ___|                     | | | |    
#| |_/ / | | \ `--. _ __ ___   ___   ___ | |_| |__  
#|    /| | | |`--. \ '_ ` _ \ / _ \ / _ \| __| '_ \ 
#| |\ \\ \_/ /\__/ / | | | | | (_) | (_) | |_| | | |
#\_| \_|\___/\____/|_| |_| |_|\___/ \___/ \__|_| |_|
#                                                   
# Copyright (c) 2024 RVSmooth
# https://gitlab.com/RVSmooth 

ROFI_DIR="$HOME/.config/rofi"
ROFI_SCRIPTS_DIR="$ROFI_DIR/scripts"
ROFI_UTILS_DIR="$ROFI_SCRIPTS_DIR/utils"
ROFI_UTILS_CMD=$(ls $ROFI_UTILS_DIR | rofi -dmenu -i -p "Utilities")

if [ -n "$ROFI_UTILS_CMD" ]; then
	bash $ROFI_UTILS_DIR/$ROFI_UTILS_CMD
else
	exit 1
fi





