#!/bin/bash
#______ _   _ _____                       _   _
#| ___ \ | | /  ___|                     | | | |
#| |_/ / | | \ `--. _ __ ___   ___   ___ | |_| |__
#|    /| | | |`--. \ '_ ` _ \ / _ \ / _ \| __| '_ \
#| |\ \\ \_/ /\__/ / | | | | | (_) | (_) | |_| | | |
#\_| \_|\___/\____/|_| |_| |_|\___/ \___/ \__|_| |_|
#
# Copyright (c) 2024 rvsmooth
# https://github.com/rvsmooth

WALLPAPER_DIR="${HOME}/Pictures/wallpapers"
APP='WallPaper'

NOTIFY() {

  notify-send --icon=preferences-wallpaper "$APP" "$@"

}

ROFI=$(find "$WALLPAPER_DIR" -name "*jpg" -name "*png" -name "*jpeg" | rofi -dmenu -p "$APP" | xargs)

