#!/bin/bash
#______ _   _ _____                       _   _
#| ___ \ | | /  ___|                     | | | |
#| |_/ / | | \ `--. _ __ ___   ___   ___ | |_| |__
#|    /| | | |`--. \ '_ ` _ \ / _ \ / _ \| __| '_ \
#| |\ \\ \_/ /\__/ / | | | | | (_) | (_) | |_| | | |
#\_| \_|\___/\____/|_| |_| |_|\___/ \___/ \__|_| |_|
#
# Copyright (c) 2024 rvsmooth
# https://github.com/rvsmooth

APP='Bzmenu'
BZ_MENU_PATH="${HOME}/.local/bin/bzmenu"

NOTIFY() {

  notify-send --icon=blueman "$APP" "$@"

}

bash -c "~/.local/bin/iwmenu --launcher rofi"


